nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: [
                "Content-Type",
                "X-Amz-Date",
                "Authorization",
                "X-Api-Key",
                "X-Amz-Security-Token",
                "X-Amz-User-Agent"
        ]
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
